### ISSUE TITLE
Add examples for distributed Torch computation

### ISSUE THREAD

**Issue by chrislusf** [chrislusf/gleam#1]

**Comment by crackerplace** [comment]
I would like to contribute to gleam either on what you are looking for "Go implementation to read Parquet files."or any other areas.I am getting into golang these days and would be eager to contribute as I like the mapreduce part.

Sorry,if this is not the right place,was not sure if I had to create a pull request and ask.

**Comment by chrislusf** [comment]
@crackerplace if just starting to learn Go, maybe you can start small first. Parquet read and write is a big task.

**Comment by crackerplace** [comment]
@chrislusf Sure, Thanks.Would work on some other part or on any issues.

**Comment by varuns-zetaris** [comment]
hi chrislusf 

I would also love to contribute to the project. I am  learning golang as of now. And would love to see this project grow.

**Comment by chrislusf** [comment]
@varuns-zetaris Thanks! Please help to test and use it first, or blog about it. I feel the installation process, docker, etc, can be much simplified.

**Comment by zhiaixuexi** [comment]
perfect!

**Comment by chrislusf** [comment]
closing this. it seems not much interest in Torch these days.
