### ISSUE TITLE
Possibility to share database connection?

### ISSUE THREAD

**Issue by forgetso** [chrislusf/gleam#101]
I have a LevelDB that can only be opened once. Therefore, when I try to open it in more than one partition I get SIGSEGV errors. Is there any way to share a database connection with the shards? I believe the connection cannot be gob encoded.

If not, it seems like my alternative would be to store copies of the DB or symlinks to the original folder as per https://stackoverflow.com/questions/9177598/multiple-instances-of-a-leveldb-database-at-the-same-time.

Appreciate any insight.

**Comment by chrislusf** [comment]
Each partition is processed by its own OS process. Not possible to share.

The symlinks could be the only option.
