### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by BruceWangNo1** [chrislusf/gleam#103]
I download the project locally following the [wiki link](https://github.com/chrislusf/gleam/wiki/Installation).
$ go get github.com/chrislusf/gleam/flow
$ go get github.com/chrislusf/gleam/distributed/gleam

But as I tried to run the word count example. The following error message showed up:
**_../github.com/chrislusf/gleam/filesystem/vfs_s3.go:10:2: cannot find package "github.com/aws/aws-sdk-go/aws" in any of:
	/usr/local/go/src/github.com/aws/aws-sdk-go/aws (from $GOROOT)_**
........................... and so on
I know I can fix this by "go get github.com/aws/aws-sdk-go/aws" and also for other missing packages. But can someone tell me what seems to be the problem?
I am using version 1.9.1 go BTW.

**Comment by chrislusf** [comment]
try go get -u

**Comment by BruceWangNo1** [comment]
Oh, Yes. That's right. Thank you. Now I feel awkward enough asking this.

**Comment by BruceWangNo1** [comment]
Fully Installation Commands For Word Count to Work:
```
$ go get -u github.com/chrislusf/gleam/flow
$ go get -u github.com/chrislusf/gleam/distributed/gleam
$ go get -u github.com/chrislusf/gleam/filesystem
$ go get -u github.com/chrislusf/gleam/plugins/file
```
