### ISSUE TITLE
backward incompatible change in github.com/xitongsys/parquet-go

### ISSUE THREAD

**Issue by yingyi-nauto** [chrislusf/gleam#105]
I imported the latest parquest-go, and got the following
vendor/github.com/chrislusf/gleam/plugins/file/parquet/parquet_file_reader.go:73: not enough arguments in call to ParquetType.ParquetTypeToGoType
        have (interface {})                                                                          
        want (interface {}, *parquet.Type, *parquet.ConvertedType)  

@xitongsys

**Comment by xitongsys** [comment]
hi, @yingyi-nauto 
I have update the code and submit a pull request.

**Comment by yingyi-nauto** [comment]
@xitongsys Thanks!
