### ISSUE TITLE
Add arguments to map functions

### ISSUE THREAD

**Issue by finder** [chrislusf/gleam#114]
Hello,

Not sure if this is possible already or is normally done in some other way, but it would be nice to add variadic arguments to registered Map Functions. For example, currently if I need to filter for a date range, I need to register a function for those specific days, and I need to know which field to use from the row.

If I could make a function that takes start_days_back and end_days_back, and date_position, I could make a more generic reusable function to do the filter that doesn't even need knowledge of the data set, but could just pull the field, compare it to the dates from the current date, and emit the result if it matches.

I think reducers could use the same functionality, but I've not run into that situation yet.

**Comment by chrislusf** [comment]
you can use a map object, so that you can "select" the values you want.

**Comment by finder** [comment]
Thanks, for others that may come on this, I found a way that you can actually achieve what I was wanting, just not dynamically, using a higher order function:

```
type RowType map[string]interface{}
func MakeMapper(fields string) gio.MapperId {
	f := func (row []interface{}) error {
		fieldNames := strings.Split(fields, ", ")
		out := make(map[string]interface{})
		for i, f := range row {
			out[fieldNames[i]] = f
		}
		gio.Emit(out)
		return nil
	}
	return gio.RegisterMapper(f)
}

var fields = "event_type, aid, time, cid, ctaid, abhash"
var mapper = MakeMapper(fields)
```

You could do the same with position args, additional arguments like start_days_back, etc.
