### ISSUE TITLE
Splitting/Unioning Flows

### ISSUE THREAD

**Issue by finder** [chrislusf/gleam#115]
I have a situation where I'm taking a large-ish cassandra table (about 40 million rows) and am processing it through multiple map/reduce pipelines, calculating into different rollup tables.

I thought I would be able to do this by just passing the same base *flow.Dataset to the different pipelines, and union'ing them at the end, but Gleam seems to freeze at pulling from Cassandra when I do this. 

First off, should this "just work"? It seems to work when I don't pass the flow to multiple branches. 

If not, is there a proper way to do this? I'm using gleam in distributed mode and in-memory.

Thanks, loving the project.

**Comment by chrislusf** [comment]
The flow maybe trying to read the data from the source concurrently. Try to
add an intermediate step.

**Comment by finder** [comment]
Thanks, there is a Map step between the cassandra pulling and where it splits. I could try to partition it or something?

	f := flow.New("Profile Rollups").
		Read(c).
		Map("Change to map", mapper)

mapper just changes it to a map from the column name

**Comment by finder** [comment]
I actually just think that I had my concurrency way too high. Lowering it to under the CPU count of a single server for Cassandra seems to have fixed it. I was trying to keep my memory usage down and noticed that a larger concurrency broke up the rows more, but caused other problems. Thanks for your help.
