### ISSUE TITLE
Missing Gleam dev slack invitation link

### ISSUE THREAD

**Issue by eiso** [chrislusf/gleam#117]
I would like to join the gleam developer slack but the link in the README is only to login.

**Comment by chrislusf** [comment]
Slack can only join by email invites. there seems a way to post a slack join link, but need to create a small web app for that.

**Comment by 1l0** [comment]
No, you don't need own server. Just create an invite link w/o expiration from invite settings.
![screen shot 2018-03-03 at 2 10 01](https://user-images.githubusercontent.com/3931445/36912005-b702e494-1e88-11e8-9104-b056f7d83ec8.png)

**Comment by chrislusf** [comment]
done. Thanks to @1l0
