### ISSUE TITLE
It is recommended to add a detailed description of the example

### ISSUE THREAD

**Issue by penhauer-xiao** [chrislusf/gleam#121]
It is recommended to add a detailed description of the update as an example, as in the example csv. Otherwise it is difficult to read.

for example csv output is 
```
000000 : %!s(<nil>) %!s(<nil>), 0 254281.5
119736 : FL CLAY COUNTY, 498960 498960
119736 : FL CLAY COUNTY, 498960 498960
206893 : FL CLAY COUNTY, 190724.4 190724.4
206893 : FL CLAY COUNTY, 190724.4 190724.4
333743 : FL CLAY COUNTY, 0 79520.76
333743 : FL CLAY COUNTY, 0 79520.76
448094 : FL CLAY COUNTY, 1322376.3 1322376.3
448094 : FL CLAY COUNTY, 1322376.3 1322376.3
```

But I don't know what it did, output the above thing

for the code:
```
a := f.Read(file.Csv("a?.csv", 3).SetHasHeader(true)).Select("select", Field(1, 2, 3)).Hint(TotalSize(17))
```
What does it mean?

then for the function 
```
Hint
```
What does it mean?

 thanks

**Comment by chrislusf** [comment]
maybe read the doc? https://godoc.org/github.com/chrislusf/gleam/flow
