### ISSUE TITLE
can i use it for my project? now?

### ISSUE THREAD

**Issue by fancyecommerce** [chrislusf/gleam#122]
您好，在知乎看到您的回答，所以，就直接用中文和您交流了。

1.您的项目目前非常稳定了吧？我是否可以使用您的gleam做公司线上项目？

2.是否有使用您的项目，做线上项目的案例？

3.我最近有一个需要使用mapreduce计算的项目？原来打算使用mongodb的mapreduce来做，看到您的这个项目想使用您的项目来做这个，不过，担心稳定性问题，做砸了要背锅

期待得到您的回复，感谢您做了这么好的开源产品分享给大家，再次感谢。

**Comment by chrislusf** [comment]
Welcome to try it out. Still beta though.
