### ISSUE TITLE
Byte Prefixed Protobuf As a Data Source

### ISSUE THREAD

**Issue by murphy214** [chrislusf/gleam#123]
Hi this could be well documented somewhere that I didn't see so apologies in advance if that is the case. 

Anyway I have a protobuf file / buffer that I've been trying to operate a mapping function on for each message within a proto structure that looks something like this. 

```
message FeatureCollection {
    repeated Feature Features = 1;
}
```

This could be like a one off use case for you guys but I already have a library that iterates through each prefix and returns the raw bytes of each "Feature" within a collection [here](https://github.com/murphy214/protoscan). Which can effectively be thought of as like splitting each line on a text file.  

My problem is the mapping part blows up in memory and I need something a little more instanced (which is where I found this project),   I'm unfamiliar with gleam's api but I could try to implement something like this for example sharding could be handled by getting positional in file relating to the start of a new prefix / feature set as opposed to one being sliced in half with a more naive split. 

Is there a like a tutorial for implementing a new data source within gleam?

Thanks in advance,
Bennett

**Comment by chrislusf** [comment]
Please check https://github.com/chrislusf/gleam/tree/master/plugins/kafka
