### ISSUE TITLE
I install gleam in centos 7, golang version 1.10.1

### ISSUE THREAD

**Issue by phamthanhlam** [chrislusf/gleam#125]
Once the libraries are installed, I run the example and receive the error message 
![loi](https://user-images.githubusercontent.com/25340581/38799159-d72307ae-418d-11e8-8e53-74699dcfefcb.PNG)
I do not know how to edit the example

**Comment by chrislusf** [comment]
update your gleam code

**Comment by phamthanhlam** [comment]
I installl go get github.com/chrislusf/gleam/flow. How do I update?
