### ISSUE TITLE
Reading Parquet from HDFS or S3

### ISSUE THREAD

**Issue by guangie88** [chrislusf/gleam#131]
Hi,

Based on the README.md, `gleam` seems to be able to read data sources (e.g. Parquet) from HDFS or S3, but there doesn't seem to be any example on this.

Is it possible to show how to read Parquet file from HDFS/S3?

Thank you.

**Comment by chrislusf** [comment]
Just change the file name from "a.csv" to "http://namenode/path/to/a.csv".

from
  f.Read(file.Csv("a.csv", 3))
to
  f.Read(file.Csv("http://namenode/path/to/a.csv", 3))

**Comment by shawel** [comment]
hey @chrislusf The solution simply appends a path to http in local file system. Are there any other configurations we need to do.

**Comment by shawel** [comment]
Hey @chrislusf,

Grabbing remote file still has issues. 
```
import (
	"github.com/chrislusf/gleam/flow"
	"github.com/chrislusf/gleam/gio"
	"github.com/chrislusf/gleam/plugins/file"
)

func ParquetMain() {
	gio.Init()
	f := flow.New("Read parquet file")
	a := f.Read(file.Csv("http://insight.dev.schoolwires.com/HelpAssets/C2Assets/C2Files/C2ImportCalEventSample.csv", 3)).Select("select", flow.Field(1, 2))
	a.Printlnf("%v, %v").Run()
}
```

`open http://insight.dev.schoolwires.com/HelpAssets/C2Assets/C2Files/C2ImportCalEventSample.csv: no such file or directory`

Best

**Comment by chrislusf** [comment]
sorry, should be "hdfs://", not "http://". I updated the first comment.

**Comment by chrislusf** [comment]
actually supporting "http://" is a good idea. I will add that.

**Comment by shawel** [comment]
hey @chrislusf  
I tried with the changes. I get different error


```
import (
	"github.com/chrislusf/gleam/flow"
	"github.com/chrislusf/gleam/gio"
	"github.com/chrislusf/gleam/plugins/file"
)

func ParquetMain() {
	gio.Init()
	f := flow.New("Read parquet file")
	a := f.Read(file.Csv("hdfs://insight.dev.schoolwires.com:80/HelpAssets/C2Assets/C2Files/C2ImportCalEventSample.csv", 3)).Select("select", flow.Field(1, 2))
	a.Printlnf("%v, %v").Run()
}
```

`failed to open file hdfs://insight.dev.schoolwires.com:80/HelpAssets/C2Assets/C2Files/C2ImportCalEventSample.csv:open /HelpAssets/C2Assets/C2Files/C2ImportCalEventSample.csv: unexpected EOF`

**Comment by chrislusf** [comment]
Is your file on hdfs?

**Comment by shawel** [comment]
No It is online in server and on s3

**Comment by chrislusf** [comment]
follow this https://github.com/chrislusf/gleam/wiki/Read-from-HDFS-Local-S3

**Comment by shawel** [comment]
ok great! thank you
