### ISSUE TITLE
HDFS package error at compiling

### ISSUE THREAD

**Issue by shang515** [chrislusf/gleam#136]
I used the "go get github.com/colinmarc/hdfs " command to get this package, but I made an error while compiling: can not find package "github.com/colinmarc/hdfs/v2/hadoopconf". Then, I downloaded the source from https://github.com/colinmarc/hdfs/releases and put it under v2, but I made an error when compiling again: "../../colinmarc/hdfs/client.go:14:2: Use of internal package not allowed"
`import (
	"context"
	"errors"
	"io"
	"io/ioutil"
	"net"
	"os"
	"os/user"
	"strings"

	"github.com/colinmarc/hdfs/v2/hadoopconf"
	hdfs "github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_hdfs"
	"github.com/colinmarc/hdfs/v2/internal/rpc"
	krb "gopkg.in/jcmturner/gokrb5.v5/client"
)`

**Comment by chrislusf** [comment]
Use go 10.3

**Comment by shang515** [comment]
I upgraded golang to 1.10.3, then executed go get github.com/colinmarc/hdfs and recompile, but still error:

../../colinmarc/hdfs/client.go:13:2: cannot find package "github.com/colinmarc/hdfs/v2/hadoopconf" in any of:
	/usr/local/Cellar/go/1.10.1/libexec/src/github.com/colinmarc/hdfs/v2/hadoopconf (from $GOROOT)
	/Users/Shared/go/src/github.com/colinmarc/hdfs/v2/hadoopconf (from $GOPATH)
../../colinmarc/hdfs/client.go:14:2: cannot find package "github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_hdfs" in any of:
	/usr/local/Cellar/go/1.10.1/libexec/src/github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_hdfs (from $GOROOT)
	/Users/Shared/go/src/github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_hdfs (from $GOPATH)
../../colinmarc/hdfs/client.go:15:2: cannot find package "github.com/colinmarc/hdfs/v2/internal/rpc" in any of:
	/usr/local/Cellar/go/1.10.1/libexec/src/github.com/colinmarc/hdfs/v2/internal/rpc (from $GOROOT)
	/Users/Shared/go/src/github.com/colinmarc/hdfs/v2/internal/rpc (from $GOPATH)

**Comment by chrislusf** [comment]
The path in the error shows you are still using 1.10.1

**Comment by shang515** [comment]
Yes, it’s already alright. Thank you.
