### ISSUE TITLE
any plan to add support golang implementation mapred for dataset?

### ISSUE THREAD

**Issue by qazqwe1596357** [chrislusf/gleam#14]
I noted gleam is not compatible with glow dataset. if some operation is easier by golang than lua script, any good idea to process this case?

**Comment by chrislusf** [comment]
Later we can use the new "plugin" system from Go 1.8, to dynamically load go lib to execute.

**Comment by qazqwe1596357** [comment]
Is that means dataset func implementation like "func (d *Dataset) Map(f interface{}) *Dataset" will be supported when gleam uses the "new 'plugin' system from Go 1.8"?

**Comment by chrislusf** [comment]
I do not know yet.
