### ISSUE TITLE
Passing command line argument to Txt reader hangs

### ISSUE THREAD

**Issue by svmhdvn** [chrislusf/gleam#142]
I'm trying to run the word count example listed in the README with a small modification:
```go
func main() {
	gio.Init()   // If the command line invokes the mapper or reducer, execute it and exit.
	flag.Parse() // optional, since gio.Init() will call this also.

	f := flow.New("top5 words in passwd").
		Read(file.Txt(os.Args[1], 2)). // <--- I have modified this line to use a CLI arg for the file path
		...
}
```
I'm running this like so:
```sh
$ ./gleamtest "/etc/passwd"
```

Running this simply hangs and I'm not sure about the cause, since I'm not passing in any other command line arguments or flags. However, running the example code from the README unmodified works just fine. What's the reason for this? Am I running this incorrectly?

EDIT: Just for clarification, I have created this file at `$GOPATH/src/siva/gleamtest/main.go` in `package main`, so the binary is named `gleamtest` accordingly.

**Comment by chrislusf** [comment]
I updated the example, using flag package to pass in CLI options.

The gleam system assumes the flag package is used.
