### ISSUE TITLE
Passing in clients to external datastores to reduce function

### ISSUE THREAD

**Issue by svmhdvn** [chrislusf/gleam#143]
I'm running a local redis cluster and trying to run a mapreduce job that will read from a file, process its contents, and write some KV pairs to the redis cluster in the reduce step. What's the correct way to pass around references to a golang redis client such as https://github.com/go-redis/redis?

What I'm trying to do is wrap the reducer function with one that I can pass the DB cluster client reference to. This is the way that seems intuitive to me, but it's currently not working:

```go
package main

import (
	"flag"
	"fmt"
	_ "log"
	_ "os"
	"strings"
	"sync/atomic"

	"github.com/chrislusf/gleam/distributed"
	"github.com/chrislusf/gleam/flow"
	"github.com/chrislusf/gleam/gio"
	"github.com/chrislusf/gleam/plugins/file"
	_ "github.com/chrislusf/gleam/util"

	"github.com/go-redis/redis"
)

var (
	isDistributed = flag.Bool("distributed", false, "run in distributed or not")
)

func main() {
	redisdb := redis.NewClusterClient(&redis.ClusterOptions{
		Addrs: []string{":7000", ":7001", ":7002", ":7003", ":7004", ":7005"},
	})
	defer redisdb.Close()

	var uid uint64 = 1

	Tokenize := gio.RegisterMapper(tokenize)
	AssignUid := gio.RegisterReducer(wrapAssignUid(&uid, redisdb))

	gio.Init()
	flag.Parse()

	f := flow.New("top5 words in passwd").
		Read(file.Txt("testfile.txt", 2)).
		Map("tokenize", Tokenize).
		Distinct("getUniqueKeys", flow.Field(1)).
		Reduce("assignUid", AssignUid)

	if *isDistributed {
		f.Run(distributed.Option())
	} else {
		f.Run()
	}
}

func tokenize(row []interface{}) error {
	sp := strings.SplitN(gio.ToString(row[0]), " ", 2)
	gio.Emit(sp[0])
	gio.Emit(sp[1])
	return nil
}

func wrapAssignUid(pUid *uint64, db *redis.ClusterClient) func(x, y interface{}) (interface{}, error) {
	return func(x, y interface{}) (interface{}, error) {
		xid := gio.ToString(x)
		fmt.Printf("Processing xid=%s now...\n", xid)
		err := db.Set(xid, atomic.LoadUint64(pUid), 0).Err()
		if err != nil {
			return nil, err
		}
		fmt.Printf("Successfully stored xid=%s\n", xid)
		atomic.AddUint64(pUid, 1)
		return y, nil
	}
}

```

**Comment by chrislusf** [comment]
Need to see the log or stack trace.

One fix: change
```
	gio.Emit(sp[0])
	gio.Emit(sp[1])
```
to
```
	gio.Emit(sp[0], sp[1])
```

**Comment by svmhdvn** [comment]
Sure, I was just testing with this very rough code, I can incorporate your fix for sure. I was more so interested in what pattern I should be following using the Gleam API. In my code right now, the reducer func that `wrapAssignUid` is wrapping doesn't actually print anything to stdout (i.e. the "Processing ..." and "Successfully stored ..." lines never print). I'm wondering if wrapping the function like so wouldn't work due to it being a closure and wrapping the reference to the redis ClusterClient.

**Comment by svmhdvn** [comment]
Found the issue and it doesn't seem very intuitive (please help me understand why this is happening). As a basis, I'm using the example code for the word counter from the README. If I make a simple change to the reducer like so:

```go
func sum(x, y interface{}) (interface{}, error) {
	xx := gio.ToInt64(x)
	yy := gio.ToInt64(y)
	fmt.Println("hello") // <--- I ADDED THIS
	return xx + yy, nil
}
```

then it gives me the following error when I run the word counter:

```sh
$ go run word_count_in_go.go
2018/11/02 19:08:13 DoMergeSortedTo failed start :ReadRow ReadMessage: Failed to read message content size 1819043176, but read only 24781: unexpected EOF
2018/11/02 19:08:13 Failed to run task sum.ReduceBy.MergeSortedTo-0: ReadRow ReadMessage: Failed to read message content size 1819043176, but read only 24781: unexpected EOF
```

Removing all `Println`s from my reducer in my original example fixes the issue and allows me to wrap the DB client as required.

**Comment by chrislusf** [comment]
use println(), which writes to stderr.

**Comment by louis83** [comment]
how to write to redis？
