### ISSUE TITLE
Define Map in golang like glow?

### ISSUE THREAD

**Issue by scalekv** [chrislusf/gleam#15]
I'd like to begin using gleam (having used glow for awhile now). Is there any way to write Map functions in golang? i.e. Is there a way to do something like the following so that I can continue to utilize go packages? Or can I only define Maps/Reduces with lua/shell scripts in gleam?

```go
package main

import (
    ".../somepackage"
    "github.com/chrislusf/gleam/flow"
)

func main() {

    flow.New().TextFile("/etc/passwd").Map(func(line string) string {
        res, _ := somepackage.Transform(line)
        return res
    }).Fprintf(os.Stdout, "%s\n").Run()
}
```

**Comment by chrislusf** [comment]
Currently only lua or external programs. External programs can be in go.

**Comment by scalekv** [comment]
Okay, thank you! I appreciate the work and the quick response.

**Comment by chrislusf** [comment]
Please let me know the use case you have in mind.

**Comment by scalekv** [comment]
No problem. Basically what I want to do is something like this:

```go
    flow.New().Source(
         // stream of protobuf messages
    ).Map(
         // demarshal protobuf
    ).Filter(
        // ...
    ).Map(
        // protobuf to json
    ).Map(
        // store into redis 
    ).Run()
```

AFAIK, to do the above in gleam I'd need some external programs or I'd need to write the logic in Lua. Both of these options create additional dependencies (e.g. a redis client library for lua or having to ship these additional binaries).

**Comment by chrislusf** [comment]
gleam can automatically ship the binaries to the remote agents for each program, same as glow. This piece of function is not turned on at this moment, but should be fairly easy to do.

**Comment by scalekv** [comment]
Do you mean it'd be easy to allow "mappers" to be written in go again, and that you'd just have to ship the binary from the driver like in glow? That'd be awesome. Glow handles my use case well right now but I would like to eventually upgrade to Gleam to take advantage of all the improvements.

Anyhow, thanks for the consideration/time.

**Comment by chrislusf** [comment]
I added an example to use Go code. It is not super nice since it is not that straight forward, but it can get the job done to run mapper in pure Go code.

See https://github.com/chrislusf/gleam/tree/master/examples/word_count_in_go

I am going to add more documentation tomorrow.

**Comment by scalekv** [comment]
Awesome! Nice that you still have a way to distribute go code. As you say, it looks a bit cumbersome at least relative to doing the same in Glow, but it does handle my use case. I'm currently prototyping a project using Glow, I'll try to adapt it to Gleam and report back.

**Comment by chrislusf** [comment]
documentation is here https://github.com/chrislusf/gleam/wiki/Write-Mapper-Reducer-in-Go

**Comment by chrislusf** [comment]
I changed the implementation overnight. Please check example and documentation again. Now it is one single binary. Just need to register the mapper or reducer at the beginning of the main program.

**Comment by scalekv** [comment]
That looks a lot more convenient! I'll try to give it a spin this week.
