### ISSUE TITLE
flow.Sort changes order of keys and values

### ISSUE THREAD

**Issue by svmhdvn** [chrislusf/gleam#151]
If I run `flow.Sort(..., flow.OrderBy(2, true))` on the row "1 2 3 4", the order of the keys and values gets changed to "2 1 3 4". However, when I run `flow.LocalSort(..., flow.OrderBy(2, true))`, the order stays the same. Is this intentional behaviour? Ideally, any operations in the flow shouldn't change the order of the keys and values unless explicitly asked for right?

**Comment by chrislusf** [comment]
local sort is done in memory, and no need to re-order.

Sort(), Distinct(), CoGroup(), etc, all change the ordering.

It is possible to add back original ordering in the Sort() step. Seems a good pull request candidate.

**Comment by jackstenglein** [comment]
@svmhdvn Hello, I know this is an old issue, but I am trying to work on this, and I can't replicate the results you're describing. Do you still have the program you used to get these results? 

Also, @chrislusf, any advice on how to add back the original ordering in the Sort step?

**Comment by chrislusf** [comment]
Actually I forgot what I mean by "add back original ordering in the Sort() step". 

Why not just add another Sort step to sort by the key?

**Comment by jackstenglein** [comment]
I was actually able to reproduce the error now. I am very new to this project, so correct me if I am wrong, but as I understand it, if I have the row `1 2 3 4`, then 1 is the key and `2 3 4` is the value. If I do Sort, then it seems like 2 becomes the key and `1 3 4` becomes the value. Is this not a bug? I don't think adding another sort step would fix the issue, because although I could make 1 the key again, I'm now sorting by the keys instead of the values.

**Comment by jackstenglein** [comment]
Here is a simple program I'm using to reproduce the error, based off the word count example on the README:

```
package main

import (
	"flag"
	"strconv"
	"strings"

	"github.com/chrislusf/gleam/distributed"
	"github.com/chrislusf/gleam/flow"
	"github.com/chrislusf/gleam/gio"
	"github.com/chrislusf/gleam/plugins/file"
)

var (
	isDistributed = flag.Bool("distributed", false, "run in distributed or not")
	Tokenize      = gio.RegisterMapper(tokenize)
	AppendRow     = gio.RegisterMapper(appendRow)
	Sum           = gio.RegisterReducer(sum)
)

func main() {

	gio.Init()   // If the command line invokes the mapper or reducer, execute it and exit.
	flag.Parse() // optional, since gio.Init() will call this also.

	f := flow.New("top5 words in passwd").
		Read(file.Txt("./test.txt", 2)). // read a txt file and partitioned to 2 shards
		Map("tokenize", Tokenize).       // invoke the registered "tokenize" mapper function.
		Map("appendRow", AppendRow).     // invoke the registered "appendRow" mapper function.
		Sort("sortByIndex2", flow.OrderBy(2, false)).
		Printlnf("%s\t%d")

	if *isDistributed {
		f.Run(distributed.Option())
	} else {
		f.Run()
	}

}

func tokenize(row []interface{}) error {
	line := gio.ToString(row[0])
	gio.Emit(strings.Fields(line)[0])
	return nil
}

func appendRow(row []interface{}) error {
	key := row[0].(string)
	intkey, _ := strconv.Atoi(key)
	row = append(row, intkey+1)
	gio.Emit(row...)
	return nil
}

func sum(x, y interface{}) (interface{}, error) {
	return gio.ToInt64(x) + gio.ToInt64(y), nil
}
```

**Comment by jackstenglein** [comment]
When I use the above program and the following test.txt file:
```
3
1
2
```

I see the following output with LocalSort:
```
3	4
2	3
1	2
```

and the following output with Sort:
```
%!s(int64=4)	%!d(string=3)
%!s(int64=3)	%!d(string=2)
%!s(int64=2)	%!d(string=1)
```

As you can see, in both cases it is sorting, but in the second case, it appears that the keys/values have flipped.

**Comment by chrislusf** [comment]
I see. It is field ordering not row ordering. Yes. This is fixable.

**Comment by jackstenglein** [comment]
I think I've narrowed the problem down to the DoMergeSortedTo function in instruction/merge_sorted_to.go. Any further advice from here would be super helpful

**Comment by chrislusf** [comment]
When on disk sorting is needed, the first field is used as the key to compare. So the ordering is changed.

When sorting is done, need to flip it back.
