### ISSUE TITLE
How to run examples on the windows

### ISSUE THREAD

**Issue by lovelly** [chrislusf/gleam#156]
How to run examples on the windows, I am running correctly in linux, but running go run word_count_in_go.go in windows cmd does not get any output.
![image](https://user-images.githubusercontent.com/13118848/54687536-cb348c00-4b56-11e9-947d-6b38b52bf8e4.png)

**Comment by chrislusf** [comment]
because the example reads the /etc/passwd file, which windows do not have.

**Comment by lovelly** [comment]
I copied passwd to the current directory.  can't find the file,  will get an error. Now the program is finished and there is no output. My environment is win10, go version 1.11.2.

**Comment by chrislusf** [comment]
Did you change the code to read from the path? Show me the code

**Comment by lovelly** [comment]
Of course, the same binary, I run with powe1rShell without output, but it is correct to run with the git bash command. I also run the same result on other computers.
![image](https://user-images.githubusercontent.com/13118848/54730166-5b5beb00-4bc2-11e9-97b5-f579592c5505.png)
![image](https://user-images.githubusercontent.com/13118848/54730302-18e6de00-4bc3-11e9-8f76-f83556ae38b4.png)

**Comment by chrislusf** [comment]
You may need to specify the parameters

-f=.\passwd

**Comment by lovelly** [comment]
I found the problem, powerShell has no tree command. Commented out code 
![image](https://user-images.githubusercontent.com/13118848/54730560-9b23d200-4bc4-11e9-9d5b-a68168379d86.png)
 I got the correct result. Does the program not output an error in this case?
