### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by kerrzhao** [chrislusf/gleam#158]
Hi

I got the error message as follow  :

[GOPM] 04-08 23:06:48 [ERROR] google.golang.org/grpc: cannot match any service
[GOPM] 04-08 23:06:48 [ERROR] google.golang.org/grpc/keepalive: cannot match any service

How to skip this step?

**Comment by chrislusf** [comment]
Do not know anything about i. Need more context.

**Comment by kerrzhao** [comment]
When I running ‘gopm get -u -v .../gleam/flow ‘

**Comment by chrislusf** [comment]
I never head of gopm before. It simply does not run for my setup.

```
chrislusf$ gopm get -u -v .../gleam/flow
[GOPM] 04-08 10:28:00 [ INFO] App Version: 0.8.8.0307 Beta
[GOPM] 04-08 10:28:00 [ INFO] Local repository path: /Users/chris/.gopm/repos
[GOPM] 04-08 10:28:00 [ INFO] Indicated GOPATH: /Users/chris/go
[GOPM] 04-08 10:28:00 [ERROR] Skipped invalid package: .../gleam/flow@branch:<UTD>
[GOPM] 04-08 10:28:00 [ INFO] 0 package(s) downloaded, 1 failed
```

**Comment by kerrzhao** [comment]
./gopm get -v -u github.com/chrislusf/gleam/flow

**Comment by kerrzhao** [comment]
> I never head of gopm before. It simply does not run for my setup.
> 
> ```
> chrislusf$ gopm get -u -v .../gleam/flow
> [GOPM] 04-08 10:28:00 [ INFO] App Version: 0.8.8.0307 Beta
> [GOPM] 04-08 10:28:00 [ INFO] Local repository path: /Users/chris/.gopm/repos
> [GOPM] 04-08 10:28:00 [ INFO] Indicated GOPATH: /Users/chris/go
> [GOPM] 04-08 10:28:00 [ERROR] Skipped invalid package: .../gleam/flow@branch:<UTD>
> [GOPM] 04-08 10:28:00 [ INFO] 0 package(s) downloaded, 1 failed
> ```

sorry, the tools problem.
