### ISSUE TITLE
Parallel Execution compile error

### ISSUE THREAD

**Issue by phuongdo** [chrislusf/gleam#16]
Parallel Execution

I did following the example in the Parallel Execution part and it did not work. There is no method found:  flow.New().Lines????. Here is my code:
`flow.New().Lines(fileNames).Partition(3).PipeAsArgs("cat $1").FlatMap(`
      function(line)
        return line:gmatch("%w+")
      end
    `).Map(`
      function(word)
        return word, 1
      end
    `).ReduceBy(`
      function(x, y)
        return x + y
      end
    `).Fprintf(os.Stdout, "%s\t%d").Run()`
 
Many thanks

**Comment by chrislusf** [comment]
changed to Strings()

See https://godoc.org/github.com/chrislusf/gleam/flow#FlowContext.Strings

**Comment by chrislusf** [comment]
Where do you see the outdated example?

**Comment by phuongdo** [comment]
I saw it in : https://github.com/chrislusf/gleam/blob/master/README.md with revision `bd0109d`  21 hours ago
@chrislusf chrislusf Update README.md
