### ISSUE TITLE
The  array item type in Map function 

### ISSUE THREAD

**Issue by kerrzhao** [chrislusf/gleam#160]
Hi
    My test data format in CSV is "6750187747,656343,3106772,1,121.430596,31.160602,"2018-06-01 15:03:49".

    `package main
import (
	. "github.com/chrislusf/gleam/flow"
	"github.com/chrislusf/gleam/gio"
	"github.com/chrislusf/gleam/plugins/file"
	"github.com/chrislusf/gleam/util"
)

var (
	FilterValid = gio.RegisterMapper(filterLog)
)

func main() {

	gio.Init()

	//fileName := "/Users/Roy/nginx_sites/gleam/examples/csv/log_campaign_branch_new_20190410.csv";
	fileName := "/Users/Roy/nginx_sites/gleam/examples/csv/log_campaign_branch_new1.csv";

	f:= New("stats branch day ").
		Read(file.Csv(fileName, 3).SetHasHeader(false)).
		Map("filterLog", FilterValid).SelectKV("select", Field(2),  Field(5,6))

	f.OutputRow(func(row *util.Row) error {
		//v :=row.V
		//fmt.Println(reflect.TypeOf(v[0]))
		return nil;
	});
	f.Run()

}

func filterLog( row []interface{}) error  {
	
	lat := gio.ToFloat64( row[4])
	println(lat)
	
	return nil
}`

The print result is : +0.000000e+000  
How to get the  correct type from Map function if the array item is float type like  "121.430596"

**Comment by chrislusf** [comment]
The row[4] is string, need to parse into float64
