### ISSUE TITLE
error when compile example

### ISSUE THREAD

**Issue by gstormlee** [chrislusf/gleam#163]
I get error when I compile example (parquet, word_count_in_pipeline, csv, word_count_in_go..)
../../plugins/file/parquet/parquet_file_reader.go:6:2: cannot find package "github.com/xitongsys/parquet-go/ParquetFile" in any of:
	/usr/local/go/src/github.com/xitongsys/parquet-go/ParquetFile (from $GOROOT)
	/Users/lwm/go/src/github.com/xitongsys/parquet-go/ParquetFile (from $GOPATH)
../../plugins/file/parquet/parquet_file_reader.go:7:2: cannot find package "github.com/xitongsys/parquet-go/ParquetReader" in any of:
	/usr/local/go/src/github.com/xitongsys/parquet-go/ParquetReader (from $GOROOT)
	/Users/lwm/go/src/github.com/xitongsys/parquet-go/ParquetReader (from $GOPATH)
../../plugins/file/parquet/parquet_file_reader.go:8:2: cannot find package "github.com/xitongsys/parquet-go/ParquetType" in any of:
	/usr/local/go/src/github.com/xitongsys/parquet-go/ParquetType (from $GOROOT)
	/Users/lwm/go/src/github.com/xitongsys/parquet-go/ParquetType (from $GOPATH)

**Comment by chrislusf** [comment]
@xitongsys could you please help here?

**Comment by xitongsys** [comment]
@chrislusf  
I have updated the parquet-go , which breaks the interface in gleam. I will update the codes. Sorry for that.

**Comment by gstormlee** [comment]
thanks a log

**Comment by xitongsys** [comment]
@gstormlee @chrislusf 
[Pull request](https://github.com/chrislusf/gleam/pull/164)

Please check. Thanks

**Comment by chrislusf** [comment]
Thanks!

**Comment by gstormlee** [comment]
I 'm sorry, I know you fixed it, but I pull  this and compile , but  I get Error.  I call it to my GOPATH/src/github.com/  , then  cd example/examples/word_count_in_go  and make.  Where am I wrong?

**Comment by chrislusf** [comment]
update the imported lib first.

```
go get -u
go build
```

**Comment by gstormlee** [comment]
thanks a lot
