### ISSUE TITLE
Is there support for scaling agents?

### ISSUE THREAD

**Issue by iselind** [chrislusf/gleam#167]
Looks like a really interesting package you have here.

I have a job that varies in load depending on the time of day. For this scenario I'd like to scale the number of workers/agents with the load. I have a few questions with this in mind.

Does Gleam support me adding more agents as needed or must all agents be started and be running from the start?

What if some agent crash or shutdown due to scaled down activity. Will some other agent re-run the job that didn't complete?

**Comment by chrislusf** [comment]
yes. you can add more agents later.

Currently the assigned job will be retried on the same instance.
