### ISSUE TITLE
Word count example in distributed mode does not work

### ISSUE THREAD

**Issue by BruceWangNo1** [chrislusf/gleam#173]
I followed the following to set the gleam cluster.

// start "gleam master" on a server
> go get github.com/chrislusf/gleam/distributed/gleam
> gleam master --address=":45326"

// start up "gleam agent" on some different servers or ports
> gleam agent --dir=2 --port 45327 --host=127.0.0.1
> gleam agent --dir=3 --port 45328 --host=127.0.0.1

Inside examples/word_count_in_go directory, I ran the following:

```bash
make run_distributed
```

The process does not seem to finish.

The following in standalone mode does not have problems.

```bash
make
```

**Comment by chrislusf** [comment]
works for me.

**Comment by BruceWangNo1** [comment]
Do I need to install LuaJIT?

**Comment by chrislusf** [comment]
no

**Comment by BruceWangNo1** [comment]
Let me attach the output.

**Comment by BruceWangNo1** [comment]
(master) word_count_in_go $ make run_distributed
go build
./word_count_in_go -distributed=true
2019/10/06 15:28:33 Start Job Status URL http://localhost:45326/job/1560264057
2019/10/06 15:28:35 127.0.0.1:45328 1:0-2:0-3:0-4:0-5:0-6:0-7:0-8:0> starting with 5 MB memory...

 ~ $ gleam master --address=":45326"
master listening on :45326
2019/10/06 15:27:45 added agent: data_center:"defaultDataCenter" rack:"defaultRack" server:"127.0.0.1" port:45327
2019/10/06 15:27:48 added agent: data_center:"defaultDataCenter" rack:"defaultRack" server:"127.0.0.1" port:45328
2019/10/06 15:28:33 1560264057 requests [cpu_count:1 cpu_level:1 memory_mb:5 ], allocated [location:<data_center:"defaultDataCenter" rack:"defaultRack" server:"127.0.0.1" port:45328 > allocated:<cpu_count:1 cpu_level:1 memory_mb:5 > ]

 Downloads $ gleam agent --dir=3 --port 45328 --host=127.0.0.1
starting in /Users/Bruce/Downloads/3
AgentServer tcp starts on 127.0.0.1:45328
AgentServer grpc starts on 127.0.0.1:55328
2019/10/06 15:27:48 Heartbeat to localhost:45326
2019/10/06 15:28:34 in memory driver_input starts writing f1560264057-d0-s0 expected reader:1
2019/10/06 15:28:34 in memory driver_output waits for f1560264057-d8-s0
2019/10/06 15:28:34 in memory driver_input finished writing f1560264057-d0-s0 202 bytes
2019/10/06 15:28:35 in memory 8:0 starts writing f1560264057-d8-s0 expected reader:1
2019/10/06 15:28:35 in memory driver_output start reading f1560264057-d8-s0
2019/10/06 15:28:35 in memory 1:0 waits for f1560264057-d0-s0
2019/10/06 15:28:35 in memory 1:0 start reading f1560264057-d0-s0
2019/10/06 15:28:35 in memory 1:0 finished reading f1560264057-d0-s0 202 bytes


 Downloads $ gleam agent --dir=2 --port 45327 --host=127.0.0.1
starting in /Users/Bruce/Downloads/2
AgentServer tcp starts on 127.0.0.1:45327
AgentServer grpc starts on 127.0.0.1:55327
2019/10/06 15:27:45 Heartbeat to localhost:45326
2019/10/06 15:27:47 deleting f411313243-d0-s0
2019/10/06 15:29:14 deleting f411313243-d0-s0
2019/10/06 15:29:27 deleting f411313243-d8-s0
2019/10/06 15:29:27 cleaning up 411313243

It just hangs there and nothing.

**Comment by chrislusf** [comment]
![Screen Shot 2019-10-06 at 12 36 23 AM](https://user-images.githubusercontent.com/1543151/66265809-662e4400-e7d1-11e9-8ec0-5935b10349bf.png)

**Comment by BruceWangNo1** [comment]
Thank you very much, Chris. It still does not work on my Macbook, though. I'm gonna test this on a server.

**Comment by BruceWangNo1** [comment]
I don't know what's wrong. It seems that one gleam agent just stuck and never went to "in memory driver_output finished reading"

MacOS environment

**Comment by BruceWangNo1** [comment]
I fixed this, temporarily. On MacOS, gleam master needs to be started by sudo. I wonder why. It possibly has something to do with "accept incoming connections."

**Comment by BruceWangNo1** [comment]
I turned off the firewall and still without sudo it did not work. I assume in the code gleam tries to access some privileged directories or files?
