### ISSUE TITLE
fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by kerrzhao** [chrislusf/gleam#178]
Hi :
     When MapReduce the 6G logs in HDFS, memory is out.

    ` := flow.New(" data").
		Read(file.Csv("hdfs://"+conf.Hdfs.Host+":"+strconv.Itoa(conf.Hdfs.Port)+conf.Hdfs.Namespace+"/data.csv", *partitionCount).SetHasHeader(false))`

   The total memory is  16G.

**Comment by chrislusf** [comment]
increase partition count

**Comment by kerrzhao** [comment]
Also,  when the partition count increased to 300.

**Comment by kerrzhao** [comment]
> increase partition count
Also, when the partition count increased to 300.

**Comment by kerrzhao** [comment]
The program died when the partition counts great than 300.
