### ISSUE TITLE
sh: ./main: No such file or directory

### ISSUE THREAD

**Issue by ggeorgiev** [chrislusf/gleam#18]
I am trying to run a very simple flow and I get `sh: ./main: No such file or directory`. It seems that it cannot find the executable that is running.

**Comment by chrislusf** [comment]
Did you use go run? Go build first.

**Comment by ggeorgiev** [comment]
I build it, and now I run the resulted binary with ./parallel and I still get `sh: ./parallel: No such file or directory`

**Comment by chrislusf** [comment]
maybe you can show me your code and how did you actually run.

**Comment by ggeorgiev** [comment]
package main

import (
	"fmt"
	"io"
	"io/ioutil"

	"github.com/chrislusf/gleam/distributed"
	"github.com/chrislusf/gleam/flow"
	"github.com/chrislusf/gleam/gio"
)

func executeTest(row []interface{}) error {
	return nil
}

func combineErrors(err1, err2 interface{}) (interface{}, error) {
	return err1.(string) + "\n" + err2.(string), nil
}

var (
	MapperExecuteTest   = gio.RegisterMapper(executeTest)
	ReduceCombineErrors = gio.RegisterReducer(combineErrors)
)

func main() {
	gio.Init()

	threads := 2
	args := "dummy"
	threadStr := make([]string, threads)
	for i := range threadStr {
		threadStr[i] = args
	}

	f := flow.New().Strings(threadStr).Broadcast(threads).Mapper(MapperExecuteTest).ReducerBy(ReduceCombineErrors).Output(func(reader io.Reader) error {
		data, err := ioutil.ReadAll(reader)
		if err != nil {
			return err
		}
		fmt.Printf(string(data))
		return nil
	})

	f.Run(distributed.Option().SetMaster(":45326"))
}


cd to the dir
go build
./parallel

2017/01/20 09:04:04 :45326 allocated 1 executors with 1 MB memory.
2017/01/20 09:04:04 127.0.0.1:45327 Broadcast.0> starting with 1 MB memory...
2017/01/20 09:04:04 :45326 allocated 1 executors with 0 MB memory.
2017/01/20 09:04:04 127.0.0.1:45327 Mapper.1-LocalSort.1-LocalReducerBy.1> starting with 0 MB memory...
2017/01/20 09:04:04 :45326 allocated 1 executors with 0 MB memory.
2017/01/20 09:04:04 127.0.0.1:45328 Mapper.0-LocalSort.0-LocalReducerBy.0> starting with 0 MB memory...
2017/01/20 09:04:04 :45326 allocated 1 executors with 20 MB memory.
2017/01/20 09:04:04 127.0.0.1:45327 MergeSortedTo.0-LocalReducerBy.0> starting with 20 MB memory...
2017/01/20 09:04:04 127.0.0.1:45327 Broadcast.0>  UserTime: 0.01s SystemTime: 0.01s
2017/01/20 09:04:04 127.0.0.1:45327 Mapper.1-LocalSort.1-LocalReducerBy.1>sh: ./parallel: No such file or directory
2017/01/20 09:04:04 127.0.0.1:45327 Mapper.1-LocalSort.1-LocalReducerBy.1>2017/01/20 09:04:04 Failed task Mapper.1-LocalSort.1-LocalReducerBy.1: Failed executing command Mapper: Mapper Wait error exit status 127.
cancel process
2017/01/20 09:04:04 127.0.0.1:45328 Mapper.0-LocalSort.0-LocalReducerBy.0>sh: ./parallel: No such file or directory
2017/01/20 09:04:04 127.0.0.1:45327 Mapper.1-LocalSort.1-LocalReducerBy.1>sh: ./parallel: No such file or directory
2017/01/20 09:04:04 127.0.0.1:45328 Mapper.0-LocalSort.0-LocalReducerBy.0>sh: ./parallel: No such file or directory
2017/01/20 09:04:04 127.0.0.1:45328 Mapper.0-LocalSort.0-LocalReducerBy.0>2017/01/20 09:04:04 Failed task Mapper.0-LocalSort.0-LocalReducerBy.0: Failed executing command Mapper: Mapper Wait error exit status 127.
2017/01/20 09:04:04 127.0.0.1:45327 MergeSortedTo.0-LocalReducerBy.0>sh: ./parallel: No such file or directory
2017/01/20 09:04:04 127.0.0.1:45327 MergeSortedTo.0-LocalReducerBy.0>2017/01/20 09:04:04 Failed task MergeSortedTo.0-LocalReducerBy.0: Failed executing command LocalReducerBy: LocalReducerBy Wait error exit status 127.

**Comment by chrislusf** [comment]
I see. When using distributed mode, add this.

  f.Run(distributed.Option().WithDriverFile())

Later I will adjust this to be a default distributed option.

**Comment by ggeorgiev** [comment]
thanks, this solved it.

**Comment by chrislusf** [comment]
Thanks! Please let me know how Gleam works for you.

**Comment by ggeorgiev** [comment]
sure, I just started, it will take some time to investigate. Thank you for putting it together.
