### ISSUE TITLE
how to set parallesim when in distributed mode

### ISSUE THREAD

**Issue by bronzels** [chrislusf/gleam#180]
i would like to try gleam as a performance optimization replace for my existing flink streaming app consuming msges comming in real time from kafka topic. in such case,  how to set parallesim when in distributed mode?

**Comment by chrislusf** [comment]
initial partitions are determined by the kafka topic.

Of course, you can always repartition it.

**Comment by bronzels** [comment]
thanks a lot chris for your reply. so partition/parallesism is the same in gleam? if want to achieve higher throughput/concurrency, just to increase the partition number is enough?
