### ISSUE TITLE
any way similiar to flink/storm keyedBy to have data specific for 1 user always go into same single partition/thread?

### ISSUE THREAD

**Issue by bronzels** [chrislusf/gleam#182]
Just as titled, which is important to have same key write/read queued in same thread to avoid concurrency conflict which requires distributed lock to fix and bad for performance.

**Comment by bronzels** [comment]
if don't get the chance to get the source data from kafka already partitioned as titled, how to do it in gleam when data for same users are mixed in different kafka partitions.

**Comment by chrislusf** [comment]
PartitionByKey will partition the data by the first field.
Use select to move the partition field to the first.
