### ISSUE TITLE
wordcount executed in testing framework with EOF errors

### ISSUE THREAD

**Issue by bronzels** [chrislusf/gleam#183]
i put wordcount example into testing framework as a case like this, always error, but no problem in exactly as the example given in gleam github home page.

**Comment by bronzels** [comment]
package test

import (
	"github.com/chrislusf/gleam/flow"
	"github.com/chrislusf/gleam/plugins/file"
	"strings"
	"testing"

	"github.com/chrislusf/gleam/gio"
)

var (
	Tokenize  = gio.RegisterMapper(tokenize)
	AppendOne = gio.RegisterMapper(appendOne)
	Sum = gio.RegisterReducer(sum)
)

func Test_Gleam_Standalone_Wordcount(t *testing.T) {
	gio.Init()   // If the command line invokes the mapper or reducer, execute it and exit.

	f := flow.New("top5 words in passwd").
		Read(file.Txt("/etc/passwd", 2)).  // read a txt file and partitioned to 2 shards
		Map("tokenize", Tokenize).    // invoke the registered "tokenize" mapper function.
		Map("appendOne", AppendOne).  // invoke the registered "appendOne" mapper function.
		ReduceByKey("sum", Sum).         // invoke the registered "sum" reducer function.
		Sort("sortBySum", flow.OrderBy(2, true)).
		Top("top5", 5, flow.OrderBy(2, false)).
		Printlnf("%s\t%d")

	f.Run()
	//t.Error("error")
}

func tokenize(row []interface{}) error {
	line := gio.ToString(row[0])
	for _, s := range strings.FieldsFunc(line, func(r rune) bool {
		return !('A' <= r && r <= 'Z' || 'a' <= r && r <= 'z' || '0' <= r && r <= '9')
	}) {
		gio.Emit(s)
	}
	return nil
}

func appendOne(row []interface{}) error {
	row = append(row, 1)
	gio.Emit(row...)
	return nil
}

func sum(x, y interface{}) (interface{}, error) {
	return gio.ToInt64(x) + gio.ToInt64(y), nil
}

**Comment by bronzels** [comment]
=== RUN   Test_Gleam_Standalone_Wordcount
Sort>Failed to read:Failed to read message: Failed to read message content size 540884285, but read only 38: unexpected EOF

2019/12/27 11:26:30 Failed to run task sum.ReduceBy.LocalSort-1: Failed to read message: Failed to read message content size 540884285, but read only 38: unexpected EOF

Sort>Failed to read:Failed to read message: Failed to read message content size 540884285, but read only 38: unexpected EOF

2019/12/27 11:26:30 Failed to run task sum.ReduceBy.LocalSort-0: Failed to read message: Failed to read message content size 540884285, but read only 38: unexpected EOF

2019/12/27 11:26:30 DoMergeSortedTo failed start :ReadRow ReadMessage: Failed to read message content size 540884285, but read only 38: unexpected EOF
2019/12/27 11:26:30 Failed to run task sum.ReduceBy.MergeSortedTo-0: ReadRow ReadMessage: Failed to read message content size 540884285, but read only 38: unexpected EOF
Sort>Failed to read:Failed to read message: Failed to read message content size 540884285, but read only 38: unexpected EOF

2019/12/27 11:26:30 Failed to run task sortBySum.LocalSort-0: Failed to read message: Failed to read message content size 540884285, but read only 38: unexpected EOF

**Comment by chrislusf** [comment]
Not designed for go tests. Need to run as an executable with main()
