### ISSUE TITLE
Does gleam have 32 bit system support?

### ISSUE THREAD

**Issue by gopricy** [chrislusf/gleam#188]
When I try to run the example pi_estimation on my RPi 4, I got the following error:
```
~/C/g/e/pi_estimation ❯❯❯ go run pi_estimation.go                                                      
# github.com/chrislusf/gleam/util                                                                      
/home/pi/go/pkg/mod/github.com/chrislusf/gleam@v0.0.0-20191006071833-08a93fce97b2/util/key.go:14:11: constant 9223372036854775807 overflows int 
```

And here is the key.go snippet. 
https://github.com/chrislusf/gleam/blob/08a93fce97b2f38d0bc58f8e4fe76b7d2553ffa9/util/key.go#L9-L15

I am pretty new to gleam, so I am not sure if this HashByKey has a presumption of running on 64 bit system. Does gleam have 32 bit system support?

**Comment by chrislusf** [comment]
try to change line 14 to just return x
