### ISSUE TITLE
Regression: unknown shorthand flag: 'g' in -gleam.mapper

### ISSUE THREAD

**Issue by ggeorgiev** [chrislusf/gleam#20]
I believe the last change leads to regression.

This is what I get for previously working scenario:

Error: unknown shorthand flag: 'g' in -gleam.mapper
Usage:
  goparallel run [flags]

Flags:
  -a, --args string     Test arguments (default "n/a")
  -b, --binary string   The binary file with the test to execute (default "n/a")
  -o, --output string   The file the output to be saved to (default "result")
  -p, --processes int   How many processes to run (default 3)
  -t, --test string     Test to be executed (default "n/a")

**Comment by chrislusf** [comment]
what's this "goparallel run"?

**Comment by ggeorgiev** [comment]
This is my app that uses gleam. Yes, I use https://github.com/spf13/cobra. What changed, it seems the previous version was not having issues with that.

**Comment by chrislusf** [comment]
Can I see your code? It seems you are using go mapper/reducer. But it would not have worked if you are using cobra. The "-gleam.mapper" has been in use for a while.

**Comment by chrislusf** [comment]
Actually I found your code in this https://github.com/chrislusf/gleam/issues/18 If you use go mappers reducers, you would need to use basic go flag package.

**Comment by ggeorgiev** [comment]
ok, thanks, I will switch to flags
