### ISSUE TITLE
FFmpeg encoding cluster !!

### ISSUE THREAD

**Issue by shahzaibcb** [chrislusf/gleam#21]
Hi Chris,

Hopes you've been doing great. Since we're using one of your product SeaWeedFS for our video streaming website as thumbs servers. It has been working dramatically great. We've around 5K concurrent requests on each thumb server & haven't encountered any I/O bottlenecks yet. Currently we've 2 x thumbs servers & soon to add more. Thanks for the great product :-) .

Getting back to the point now, as we've video streaming website where users upload videos, servers encode it with ffmpeg/imagick & store it into storages for serving over HTTP, we're currently striving to make encoding faster since our encoding servers are very simple, each video gets encoded on single server  what we're looking for is Encoding cluster where single video can be encoded into multiple servers. 

I was looking at different solutions but looks like there are not much available & thought if i could ask for your advice if Gleam can be used as encoding cluster or if you've something better suggestion it'd be really helpful?

Thanks a lot for all the work & efforts :)

Regards.
Shahzaib

**Comment by chrislusf** [comment]
Thanks for the nice words about SeaweedFS. Maybe you can write about your use case and share it on some blog.

What you are looking for is a job queue, which should have many implementations already and is different from what Gleam is created for.
