### ISSUE TITLE
The datasets can be cached in memory？

### ISSUE THREAD

**Issue by z80sui** [chrislusf/gleam#27]
I want to find a way to use distributed computation system for  computing datasets cached in memory.
The datasets only load in one time,and cached in memory.
Can the gleam help me ?
Tks very much!

**Comment by chrislusf** [comment]
Let me know your use case.

**Comment by z80sui** [comment]
There are a lot of data on hdfs,more than 1000G. 
I would like to use this system to load the data into memory, so I can submit some jobs directly using the data in memory to calculate the output.Like spark share rdd.

**Comment by chrislusf** [comment]
There is a HashJoin() function to keep the smaller dataset in memory.

The other steps all work in a streaming way, unless blocking steps such as LocalSort().

I want to know what operations you need to do.
