### ISSUE TITLE
Dynamic Source, or Multiple Pass Flow

### ISSUE THREAD

**Issue by wenkesj** [chrislusf/gleam#30]
Is it possible to modify a **Source** such that the next time `fc.Run()` is called, the new source is called and updated as well? This would give the "illusion" of state... maybe that defeats the purpose of a DAG...

## What I am trying
```go
fc.Source(...).Map(...).Reduce(...).Output(...)
fc.Run()
// ... Wait
// Update fc.Source(...) or reset the source so that Run calls the source function again?
fc.Run()
```

## What I want to accomplish
Basically, I would like to accomplish something like this:
```
Run => flow.Source() -> (Some Mappers/Reducers) -> flow.Output() -> (Update flow.Source)
Run()
Run()
...
Run()
... And so on...
```

I understand the idea behind Directed **Acyclic** Graphs and that this kind of defeats the purpose, but maybe you could help point me in the right direction... Essentially, I want to accomplish state by passing new source information based on what was collected previous.

Thank you for you help.

**Comment by chrislusf** [comment]
Understood. 

But the flow object has some states. For example, the distributed execution engine will retry failed steps for the same flow. If the flow is reused, it will cause confusion to the execution engine.

It's better to just create a new flow object. It's not so expensive.

**Comment by wenkesj** [comment]
That makes sense. Thanks!

**Comment by wenkesj** [comment]
@chrislusf This is essentially the idea, just adding this for a fun, trivial example:

```go
func Forward(input ...interface{}) []interface{} {
  wg.Add(1)
  var output []interface{}
  go func () {
    flow.New().
      Source(func(writer io.Writer) error {
        return util.WriteRow(writer, input...)
      }).
      Mapper(mapperSum).
    	ReducerBy(reducerSum).
      Output(func(reader io.Reader) error {
    		defer wg.Done()
		var err error
    		output, err = util.ReadRow(reader)
    		return err
    	}).Run()
  }()
  wg.Wait()
  return output
}
```
And calling this

```
func main() {
	runs := 10
	input := 1
	for i := 0; i < runs; i++ {
		output := Forward(input)
		input = int(output[1].(uint64))
		fmt.Println("output at ", i, ":", input)
	}
}
```

**Comment by liuluheng** [comment]
maybe this is a simple iterative algorithm.:)
