### ISSUE TITLE
is the Lua neccesary for this project, I am run the word count program,it occur some errors,i am not install the Lua in my os!

### ISSUE THREAD

**Issue by zhangweilun** [chrislusf/gleam#34]
os : Mac 10.3
error:
/usr/local/Cellar/go/1.8/libexec/bin/go run /Users/willian/Desktop/project/bigdata/session/src/github.com/zhangweilun/session/session.go
Running in standalone mode.
sh: ./session: No such file or directory
sh: ./session: No such file or directory
sh: ./session: No such file or directory

**Comment by chrislusf** [comment]
yes

**Comment by chrislusf** [comment]
go run is not supported

**Comment by zhangweilun** [comment]
thanks for you answer!

**Comment by zhangweilun** [comment]
if you are not busy, please do me a favor, the document do not say how to run the example code program, if you are free, just tell some tips,i use the spark before, I know mabey have a driver program, but I am not find in the documents, if there be, please give a url to point the page.
