### ISSUE TITLE
I am running a very easy word count, and I would like to see the data when map working.

### ISSUE THREAD

**Issue by zhangweilun** [chrislusf/gleam#36]
I add a statement on map processing,

func tokenize(row []interface{}) error {
	line := string(row[0].([]byte))

	fmt.Println(row[0]) // I add
	fmt.Println(line) // I add 
	for _, s := range strings.FieldsFunc(line, func(r rune) bool {
		return !('A' <= r && r <= 'Z' || 'a' <= r && r <= 'z' || '0' <= r && r <= '9')
	}) {
		gio.Emit(s)
	}
	return nil
}

when I added, there is a error,i want to know how to println the data when Map or reduce working, and how should I do 

there is the error:
➜  session git:(master) ✗ ./session 
Running in standalone mode.
2017/04/25 17:30:43 Failed to execute mapper [./session -gleam.mapper=m2]: input row error: Failed to read message content size 540357467, but read only 40020: unexpected EOF

**Comment by chrislusf** [comment]
Please show the full source code.
