### ISSUE TITLE
about gleam's RPC framework

### ISSUE THREAD

**Issue by hxiaodon** [chrislusf/gleam#4]
Hi, Chris:

Did you consider about adopting the [GRPC](https://github.com/grpc/grpc-go) solution for gleam?  Current gleam use raw protobuf with self-maintained dispatching/marshaling logic, I feel that the GRPC(http2+protobuf+rpc framework) will provide an evident assistance for gleam.

GPRC is a mature tech while my current project has involved in for more than one year~

Thanks!

**Comment by chrislusf** [comment]
Thanks! I will use it where it best fits.
