### ISSUE TITLE
Is there is any example usage case in streaming processing?

### ISSUE THREAD

**Issue by qazqwe1596357** [chrislusf/gleam#45]
Is there is any example usage case in streaming processing?

Like the Driver is keep alive, and keep read from one streaming source like kafka,
process each data batch and send to a streaming output like kafka.

Some question:
    1. Is any "example usage case" or "best practices" to process streaming data?
    2. If Gleam does work, whether need to restart one Gleam each "streaming data slice"?
        Like Kafka source, whether need to reconnect to the broker list each time?
    3. For the result each batch done, whether Gleam support any method to keep some "dataset" for next batch? Or a mechanism to support "Global Context Dataset" across Different Gleam batch?
    4. Whether support one mechanism like one "Never Stop" distributed mapper can produce "streaming data slice" dataset, and trigger the slice dataset batch to run in sequence? To avoid recronnect to kafka.
    5. Any orhter Idea is help to processing streaming data?

thanks~

**Comment by chrislusf** [comment]
Gleam can work in a streaming way, but the full support is working in progress. Just added timestamp to each message in https://github.com/chrislusf/gleam/pull/44 , and will be working on adding sliding window support, and other missing parts.

**Comment by chrislusf** [comment]
1. not yet.
2. no.
3. sliding window will support this.
4. yes.
5. ...

**Comment by qazqwe1596357** [comment]
Thans for the answer~ Expect the new features.

**Comment by qazqwe1596357** [comment]
I have some more questions about mechanism design.

1. Executer process different step at same time，or All data in one step batch is done then next step start？

2.  Can I think that local mode and distributed mode, inter-section communication form of the interface form and the general structure of the same, but the distributed mode using RPC way for data transmission, the local channel can be used directly in the form of transmission? The difference between the two data pipeline and the process of deployment only?

thanks a lot~

**Comment by chrislusf** [comment]
1. Both are possible. Processes start when input sources are available and execution resources are available. 
2. Mostly correct.

**Comment by qazqwe1596357** [comment]
thanks ~

**Comment by qazqwe1596357** [comment]
Continue some more questions about mechanism design In my learning.

    1. I note that the kafka source is seems like keep consuming messages in mappers. Then the dataset is a Infinity data. is this Right?

    2. If Q1 is right, in current project progress, the function can use in steps/tasks is under some limit, function like sort, can not support, because there is no boundary for the dataset?

    3. If Q1 or Q2 is wrong, how can I run reduce like operation on the kafka source produced dataset In right way?

    4. Is "sliding window" you said above is the method to solve my confused in this questions? And  "sliding window" means to split a Infinity dataset to small parts?

**Comment by chrislusf** [comment]
1. yes
2. correct
3. currently no.
4. yes. yes.
5. to be designed. Not finalized yet.

**Comment by qazqwe1596357** [comment]
thanks a lot ~

**Comment by qazqwe1596357** [comment]
I come again~
I need to confirm that the use of some of the core data structure of my understanding is correct.

## 1. About DAG
- Dataset: Operable logically "atomic data representation" in one DAG. Use "Step" to transform DatasetA to DatasetB.
- Step: "atomic Transform action" between two Dataset.

- Dataset Action(like Map, reduce, sort ...):
    - Some of the more commonly used transformations logic, or some "transformations framework".
    - One "Dataset Action" may has one or more Steps.

## 2. About Run time
- Dataset Shards: The Dataset physical realization, or say "atomic data" can be processed in physical.
- Tasks: During the running of Step, the specific "thread" bound to one "Task".

- AND "Dataset, Step" is more relevant to the Plan of DAG;
- AND "Dataset Shards, Tasks" is more relevant to execution.

3. About Step Logical realization
- Step contains 4 kinds of substructures associated with the run logic. Function, Instruction, Script, Command.
- Function, Command: This two is the basis of the "Executable Unit", a Step can run one of them.
- Instruction is more like a framework to generate Function.
    - Instruction some like "Map / Reduce ..." relative to the step relationship,
    - But it seems One Instruction generate one Function to run in one step.
- Script is more like a framework to generate Command. Just Like Instruction To Function.

4. Some Idea for Streaming Process:
    1) The Operation LocalSort cant't "eat one, spit one" just like Map Operation.
       Beacuse LocalSort wait for all lines in this Shard for this Task, and then sort it.
    2) The Operation Partition Is NOT a block Operation like LocalSort.
    3) If I keep a context in the Task, and then use this "context" to filter each input,
        I can do a full real-time processing.
    4) I can use Partition and my own implementation Operation which "has a filter with context",
       to achieve a full real-time like Group operation.
    5) I can Use The timestamp and just wait for all lines in this "time window" like LocalSort,
        and then sort the lines, then send the results.
        In this way, I can Get a "window sort" for small batch processing just like spark streaming.

**Comment by chrislusf** [comment]
Good write up. You could turn this into a blog post.

**Comment by qazqwe1596357** [comment]
Is any mistake in my understanding above?

**Comment by chrislusf** [comment]
Nothing wrong.

**Comment by qazqwe1596357** [comment]
thanks a lot ~

**Comment by xiumu-beta** [comment]
hello, is the `slide window` being developed ? 

I expect that.  Thanks.
