### ISSUE TITLE
RFC: removing Lua support?

### ISSUE THREAD

**Issue by chrislusf** [chrislusf/gleam#49]
How about we remove Lua support from Gleam?

This is because of:

1. Complexity to install Gleam. Although installation is fairly easy, installing Lua and the message pack library are still extra steps.

2. Complexity to support Lua. To support a scripting language, I need to support serialization and deserialization between MsgPack and Lua in memory data row, meta data, etc. This makes adding new features, such as windowing, watermark, etc, more complicated.

3. Lua has several flavors. Impossible to support and test all of them. Currently it is already limited to only LuaJit. The pure Go interpreters for Lua do not work due to subtle details. And they are yet another flavor of Lua.

4. Lua's nil in the array is causing truncated rows.

5. Lua treat both []byte and string as string. Losing type information during SerDe.

If removing Lua,

1. Conceptually much simpler to add new Gleam features. Being an open source project, this is very important to move this project forward.

2. Conceptually much simpler to deploy.

3. No need for Go developers to learn Lua. Lua is simple, but hidden pitfalls are not obvious to beginners.

4. One way to write Gleam code. Multiple ways to do one thing is not Go style.

**Comment by SuperGod** [comment]
If removed lua,What is the difference with Glow?
I think you can split lua support to a new project, it maybe supported   by somebody who use it

**Comment by chrislusf** [comment]
Moved the existing branch that has lua support to:
  https://github.com/chrislusf/gleamold
