### ISSUE TITLE
Improve test coverge.

### ISSUE THREAD

**Issue by hackintoshrao** [chrislusf/gleam#5]
I would like to learn more about the project by getting started with contributing to the tests to improve the coverage. I believe that would a productive start to understand the project.

**Comment by chrislusf** [comment]
Yes!!!

The test coverage is so low that I can not get it listed on the "awesome go" list.

Please just let me know which package you are going to work on.

**Comment by hackintoshrao** [comment]
Let me know whats the easiest to get started with? That'll help me understand the other pieces of the puzzle too.

**Comment by hackintoshrao** [comment]
@chrislusf : Will you be available on IRC/Gitter/Slack for communication so that I could ping you for some questions whenever I need some help while contributing? Closing the issue, will consistently contribute towards fixing it.

**Comment by chrislusf** [comment]
ok. I just created slack https://gleam-dev.slack.com

**Comment by hackintoshrao** [comment]
It looks I need an invite to join. Can you send a invite to `kartronics85@gmail.com` .

**Comment by hackintoshrao** [comment]
Got it, Thanks.

**Comment by sumitgs** [comment]
Can you send an invite to sumitgajjar02@gmail.com?

**Comment by sumitgs** [comment]
Thanks.
