### ISSUE TITLE
Is the Lua script Map/Reduce API discarded?

### ISSUE THREAD

**Issue by carusyte** [chrislusf/gleam#51]
I've just found the closed issue about this feature being moved to another project [issue#49](https://github.com/chrislusf/gleam/issues/49), but part of the wiki or readme still mentioning Lua/LuaJIT/MessagePack.lua is kind of confusing or misleading :)

**Comment by chrislusf** [comment]
let me know which page you see it.

**Comment by carusyte** [comment]
The README.md about setting up gleam cluster:
//if a different server, remember to install Luajit and copy the MessagePack.lua file also.

[The wiki about Map function](https://github.com/chrislusf/gleam/wiki/Map)
