### ISSUE TITLE
Consider utilizing package version management tools

### ISSUE THREAD

**Issue by carusyte** [chrislusf/gleam#54]
As gleam's API is changing, our code which relies on the stability of gleam API becomes unstable. Please consider utilizing some of the available package versioning tools such as [gopkg.in](http://labix.org/gopkg.in).

**Comment by chrislusf** [comment]
Please bear with me for the last few days' changes. Doing a rewrite recently.

**Comment by chrislusf** [comment]
please use glide or some other client side versioning for now.
