### ISSUE TITLE
Can't collect all of the expected rows in OutputRow

### ISSUE THREAD

**Issue by carusyte** [chrislusf/gleam#55]
Say I submit a source of slice[53][1], I am expecting to get the final reduced output of the same number of rows, 53. But I get only 18, which means 35 of them are lost.
<img width="1197" alt="screen shot 2017-08-28 at 5 52 08 pm" src="https://user-images.githubusercontent.com/1680881/29768868-7882a3a4-8c1a-11e7-8c93-4555922c9cb8.png">
<img width="1184" alt="screen shot 2017-08-28 at 5 54 23 pm" src="https://user-images.githubusercontent.com/1680881/29768879-7fedbd90-8c1a-11e7-82d2-06b4e431ec72.png">
<img width="1178" alt="screen shot 2017-08-28 at 5 52 51 pm" src="https://user-images.githubusercontent.com/1680881/29768892-8bb98b40-8c1a-11e7-88ba-83c623545271.png">

Flow creation code:

> 	f := flow.New("KDJ Score Calculation").Slices(mapSource).RoundRobin("rr", int(shard)).
		Map("kdjScorer", KdjScorer).
		ReduceBy("kdjScoreCollector", KdjScoreCollector, sortOption).
		OutputRow(func(r *util.Row) error {
		logr.Debugf("Output Row: %+v", r)
		rep.RowIds = append(rep.RowIds, r.K[0].(string))
		rep.Scores = append(rep.Scores, r.V[0].(float64))
		return nil
	})

**Comment by chrislusf** [comment]
Reducer will affect the row count.

**Comment by carusyte** [comment]
I've placed log message before calling gio.Emit(rowId, s) in the reducer, and I've checked the log file and counted the message, it all sums to 53, which matches the input size. Kind of weird...
Here is my reducer function, if it may help investigating the issue. 
```
func kdjScoreMapper(row []interface{}) error {
	s := .0
	//interpRow(row)
	m := row[0].([]interface{})[0].(map[interface{}]interface{})
	//in := row[0].([]interface{})[0].(*KdjScoreCalcInput)
	log.Printf("kdj score mapper receive row len: %d, row[0] len: %d,"+
		" parse map from input: %+v", len(row), len(row[0].([]interface{})), m)
	buyDay, sellDay, e := getKDJfdViews(model.DAY, int(gio.ToInt64(m["DayLen"])))
	if e != nil {
		return e
	}
	sdy, e := calcKdjScore(m["KdjDay"].(map[interface{}]interface{}), buyDay, sellDay)
	if e != nil {
		return e
	}
	buyWeek, sellWeek, e := getKDJfdViews(model.WEEK, int(gio.ToInt64(m["WeekLen"])))
	if e != nil {
		return e
	}
	swk, e := calcKdjScore(m["KdjWeek"].(map[interface{}]interface{}), buyWeek, sellWeek)
	if e != nil {
		return e
	}
	buyMonth, sellMonth, e := getKDJfdViews(model.MONTH, int(gio.ToInt64(m["MonthLen"])))
	if e != nil {
		return e
	}
	smo, e := calcKdjScore(m["KdjMonth"].(map[interface{}]interface{}), buyMonth, sellMonth)
	if e != nil {
		return e
	}
	wgtDay := gio.ToFloat64(m["WgtDay"])
	wgtWeek := gio.ToFloat64(m["WgtWeek"])
	wgtMonth := gio.ToFloat64(m["WgtMonth"])
	s += sdy * wgtDay
	s += swk * wgtWeek
	s += smo * wgtMonth
	s /= wgtDay + wgtWeek + wgtMonth
	s = math.Min(100, math.Max(0, s))

	rowId := m["RowId"].(string)
	//gio.Emit([]float64{s})
	log.Printf("%s calculated score: %f, emitting", rowId, s)
	gio.Emit(rowId, s)
	//gio.Emit("KDJS", 2.13)

	return nil
}
```

**Comment by carusyte** [comment]
I added some debug message and probably some other irrelevant adjustments in both the mapper and reducer, the problem just mysteriously disappeared! Trying to figure this out...
I noticed that in the job report screenshots I just posted, some of the agent server seems not sending any results out:
<img width="1197" alt="screen shot 2017-08-28 at 5 52 08 pm" src="https://user-images.githubusercontent.com/1680881/29782494-5b75b622-8c4f-11e7-9695-617aeb36f2a4.png">
The 3rd step is named "kdjScoreCollector.ReduceBy.LocalSort", don't know what it means exactly but now when everything seems fine they reads like "3:6 4=>4", instead of "3:6 0=>0", guess that means no input was sent to that 3rd step on that agent server?

**Comment by chrislusf** [comment]
What's in your reducer?

**Comment by carusyte** [comment]
I just reverted my driver program back to the problematic version and reproduced the issue. The biggest difference I can see is that there are much more log messages coming out from native log or logrus. 
Here's my file compare report by Beyond Compare (don't know how to link to github's file history comparison yet, forgive me for the inconvenience):
[Report.html.zip](https://github.com/chrislusf/gleam/files/1258867/Report.html.zip)
The problematic version is on the left.

**Comment by chrislusf** [comment]
can not tell. nothing obvious.

I can only think of this, but seems you are not doing this:
"Try to avoid logging to os.Stdout, and only log to os.Stderr."

**Comment by carusyte** [comment]
Thank you. I'll keep that in mind.
