### ISSUE TITLE
the demands about "Read Parquet files".

### ISSUE THREAD

**Issue by lewgun** [chrislusf/gleam#64]
Hey chrislusf:
     I talked with xitongsys who is the owner of  [parquet-go](https://github.com/xitongsys/parquet-go/) about gleam, he likes to help with "Read Parquet files" , he is rewriting it now, he wants to know the demands in the gleam, could you list some at [here](https://github.com/xitongsys/parquet-go/issues/1)?

**Comment by chrislusf** [comment]
That's super!

All the ORC file reader is very similar to parquet reader. All ORC related content is in this single file:

https://github.com/chrislusf/gleam/blob/master/plugins/file/orc/orc_file_reader.go
