### ISSUE TITLE
Read from parquet file

### ISSUE THREAD

**Issue by xitongsys** [chrislusf/gleam#82]
Hi, @chrislusf , parquet-go is finished now. https://github.com/xitongsys/parquet-go
It supports almost all features in parquet. I will read the gleam code this week and try to add the parquet reader. You can also see my code and give some requirements or test it :)
Thanks

**Comment by chrislusf** [comment]
any updates?

**Comment by xitongsys** [comment]
@chrislusf Sorry about the delay. It takes me a lot of time to upgrade the parquet-go. 
Good news is the parquet-go is much more robust and higher performance than before. 
I will apply it in gleam as soon as possible :)

**Comment by xitongsys** [comment]
hi, @chrislusf 
I add the parquet reader and submit a pull request. Please test and check it.
