### ISSUE TITLE
Read from Kafka

### ISSUE THREAD

**Issue by yingyi-nauto** [chrislusf/gleam#97]
Hi,
I am trying to run the kafka reader example, but getting the following error. It seems that the Kafka plugin stuck at the Read.Map step.

```
step:<topic>.list0
  output : d0
     shard:0 time:11.505ms completed 3630
     ...
step:<topic>.RoundRobin1
  input  : d0
     shard:0 time:11.505ms completed 3630
     ...
  output : d1
     shard:0 time:17.107ms completed 227
     ...
step:<topic>.Read.Map2
  input  : d1
     shard:0 time:17.107ms completed 227
     ...
  output : d2
     shard:0 time:2m21.86562s processed 0
     ...

Failed to process output: Failed to read message: Failed to read message content size 1684104562, but read only 24060620: unexpected EOF

step.go:58: Failed to run task Output-0: Failed to read message: Failed to read message content size 1684104562, but read only 24060620: unexpected EOF
```

**Comment by chrislusf** [comment]
could be due to different kafka versions.

**Comment by yingyi-nauto** [comment]
@chrislusf I have kafka 0.10.1, not old but also not the latest. It seems that if I put the flow definition and run inside a `github.com/codegangsta/cli` sub command, I will get this issue. If I put flow definition and run in main, it works fine.

Another question here: how gleam handles the errors emit from mappers? Is there any way that I could keep metrics of errors from different mappers?

Thanks!

**Comment by chrislusf** [comment]
I see. This is not related to Kafka. Gleam needs to run via normal CLI via "flag" package, not some other sub command.

Gleam currently only print out the errors back to the driver console. Later we need a new way to intercept the errors.
